* Q1 The key could be already in use on other github projects as deploy key
** A1
that's a bit tricky to find but run
ssh -T -ai ~/.ssh/KEY_NAME git@github.com
** A2:
https://stackoverflow.com/questions/21160774/github-error-key-already-in-use
*** file example
## file:: c:/Users/48944/.ssh/config
# Default GitHub
Host github.com
  HostName github.com
  User git
  IdentityFile ~/.ssh/id_rsa

Host git-anything
  HostName github.com
  User git
  IdentityFile ~/.ssh/git_anything_rsa

*** file example
## file:: c:/Users/48944/anything/.git/config as:
...
[remote "origin"]
	url = git@git-anything:lsy83971/anything.git
...

* Q2: something about emacs company beckends 
** A2
https://www.youtube.com/watch?v=zSPraaX2524
(set (make-local-variable 'company-backends)
 '((company-yasnippet company-elisp...) (...))
)
(setq company-idle-delay 0)
(setq company-idle-delay 0)
(make-variable-buffer-local 'company-minimum-prefix-length')

company-active-map
(define-key company-active-map (kbd "M-.") 'company-filter-candidates)
(define-key company-active-map (kbd "M-,") 'company-abort)

avy-goto

*** usage of setq
*** usage of make-variable-buffer-local

*** optional param & &rest &optional
(funcall (lambda (n &rest ns)
(+ n (apply '+ ns)))1 2 3 4 5)

*** constant symbol :
it is a symbol used as variable description






* Q3 write a rgrep project 
a -- Function name: symbol with a function definition.
b -- Name of existing buffer.
B -- Name of buffer, possibly nonexistent.
c -- Character (no input method is used).
C -- Command name: symbol with interactive function definition.
d -- Value of point as number.  Does not do I/O.
D -- Directory name.
e -- Parameterized event (i.e., one that¡¯s a list) that invoked this command.
     If used more than once, the Nth ¡®e¡¯ returns the Nth parameterized event.
     This skips events that are integers or symbols.
f -- Existing file name.
F -- Possibly nonexistent file name.
G -- Possibly nonexistent file name, defaulting to just directory name.
i -- Ignored, i.e. always nil.  Does not do I/O.
k -- Key sequence (downcase the last event if needed to get a definition).
K -- Key sequence to be redefined (do not downcase the last event).
m -- Value of mark as number.  Does not do I/O.
M -- Any string.  Inherits the current input method.
n -- Number read using minibuffer.
N -- Numeric prefix arg, or if none, do like code ¡®n¡¯.
p -- Prefix arg converted to number.  Does not do I/O.
P -- Prefix arg in raw form.  Does not do I/O.
r -- Region: point and mark as 2 numeric args, smallest first.  Does no I/O.
s -- Any string.  Does not inherit the current input method.
S -- Any symbol.
U -- Mouse up event discarded by a previous k or K argument.
v -- Variable name: symbol that is ¡®custom-variable-p¡¯.
x -- Lisp expression read but not evaluated.
X -- Lisp expression read and evaluated.
z -- Coding system.
Z -- Coding system, nil if no prefix arg.


* Q4 pycharm
search everywhere: double shift
goto file 




